### ISSUE TITLE
Wrong image URL reference in /challenges/forensics/blur_image/writeup.md

### ISSUE THREAD

**Issue by l3ouu4n9** [wat3vr/watevrCTF-2019#1]
Hello,

It is not a big issue. I just notice that in the file [https://github.com/wat3vr/watevrCTF-2019/blob/master/challenges/forensics/blur_image/writeup.md](url) 

The content
`https://github.com/mateuszdrwal/watevrCTF-2019/blob/release/challenges/forensics/blur_image/filter.png`
should be replaced with
`https://github.com/wat3vr/watevrCTF-2019/blob/master/challenges/forensics/blur_image/filter.png`
for the image to show up.

**Comment by mateuszdrwal** [comment]
thanks, fixed
